-- =============================================================
-- GOODLUCK TECH SERVICE — SUPABASE POSTGRESQL DATABASE SCHEMA
-- =============================================================
-- Copy and run this script in your Supabase SQL Editor:
-- https://app.supabase.com/project/_/sql

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  condition TEXT NOT NULL DEFAULT 'UK Used',
  base_price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_status TEXT NOT NULL DEFAULT 'In Stock',
  description TEXT,
  warranty TEXT DEFAULT '6 Months Warranty',
  battery_health TEXT DEFAULT '90%+',
  sim_info TEXT DEFAULT 'Physical SIM + eSIM',
  is_featured INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. VARIATIONS TABLE
CREATE TABLE IF NOT EXISTS public.variations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  storage TEXT,
  ram TEXT,
  color TEXT,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_qty INT DEFAULT 5,
  sku TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCT IMAGES TABLE
CREATE TABLE IF NOT EXISTS public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  sort_order INT DEFAULT 0
);

-- 4. ACCESSORIES TABLE
CREATE TABLE IF NOT EXISTS public.accessories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_qty INT DEFAULT 10,
  image_url TEXT,
  description TEXT,
  is_featured INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. PRODUCT ACCESSORIES LINK TABLE
CREATE TABLE IF NOT EXISTS public.product_accessories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  accessory_id BIGINT REFERENCES public.accessories(id) ON DELETE CASCADE
);

-- 6. BRANDS TABLE
CREATE TABLE IF NOT EXISTS public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  is_active INT DEFAULT 1
);

-- 7. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_method TEXT NOT NULL,
  state TEXT,
  city TEXT,
  address TEXT,
  notes TEXT,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  order_details JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. REPAIR REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.repair_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  email TEXT,
  location TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  storage TEXT,
  problem_type TEXT NOT NULL,
  problem_description TEXT,
  repair_preference TEXT DEFAULT 'Bring to store',
  preferred_date TEXT,
  diagnosis TEXT,
  estimated_cost NUMERIC(12, 2) DEFAULT 0.00,
  final_cost NUMERIC(12, 2) DEFAULT 0.00,
  internal_notes TEXT,
  images JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. SWAP / TRADE-IN REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.swap_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_code TEXT UNIQUE NOT NULL,
  request_type TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  location TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  storage TEXT NOT NULL,
  ram TEXT,
  color TEXT,
  battery_health TEXT,
  condition_notes TEXT,
  faults TEXT,
  asking_price NUMERIC(12, 2) DEFAULT 0.00,
  target_swap_phone TEXT,
  admin_offer NUMERIC(12, 2) DEFAULT 0.00,
  internal_notes TEXT,
  images JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  rating INT NOT NULL DEFAULT 5,
  comment TEXT NOT NULL,
  verified_purchase INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 12. ADMIN USERS TABLE
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================
-- SEED INITIAL DATA FOR NIGERIAN PHONE STORE INVENTORY
-- =============================================================

-- Seed Admin User Credentials
INSERT INTO public.admin_users (email, password, role) VALUES
  ('goodlucktech16@gmail.com', 'GGodluck1990', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Default Store Settings
INSERT INTO public.settings (key, value) VALUES
  ('store_name', 'Goodluck Tech Service'),
  ('store_address', 'UPTH 18, Everyday Plaza, Choba, Port Harcourt, Rivers State'),
  ('whatsapp_number', '09012544042'),
  ('phone_number', '09012544042'),
  ('email', 'info@goodlucktech.ng')
ON CONFLICT (key) DO NOTHING;

-- Brands
INSERT INTO public.brands (name, logo_url) VALUES
  ('Apple', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg'),
  ('Samsung', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg'),
  ('Tecno', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Tecno_Mobile_logo.svg'),
  ('Infinix', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Infinix_logo.svg'),
  ('Google Pixel', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg')
ON CONFLICT (name) DO NOTHING;

-- Enable Public Access Row Level Security (RLS) Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accessories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repair_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swap_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public write access on products" ON public.products FOR ALL USING (true);

CREATE POLICY "Allow public read access on variations" ON public.variations FOR SELECT USING (true);
CREATE POLICY "Allow public write access on variations" ON public.variations FOR ALL USING (true);

CREATE POLICY "Allow public read access on product_images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Allow public write access on product_images" ON public.product_images FOR ALL USING (true);

CREATE POLICY "Allow public read access on accessories" ON public.accessories FOR SELECT USING (true);
CREATE POLICY "Allow public write access on accessories" ON public.accessories FOR ALL USING (true);

CREATE POLICY "Allow public read access on orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public write access on orders" ON public.orders FOR ALL USING (true);

CREATE POLICY "Allow public read access on repair_requests" ON public.repair_requests FOR SELECT USING (true);
CREATE POLICY "Allow public write access on repair_requests" ON public.repair_requests FOR ALL USING (true);

CREATE POLICY "Allow public read access on swap_requests" ON public.swap_requests FOR SELECT USING (true);
CREATE POLICY "Allow public write access on swap_requests" ON public.swap_requests FOR ALL USING (true);

CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public write access on settings" ON public.settings FOR ALL USING (true);

CREATE POLICY "Allow public read access on admin_users" ON public.admin_users FOR SELECT USING (true);
CREATE POLICY "Allow public write access on admin_users" ON public.admin_users FOR ALL USING (true);
