-- =============================================================
-- GOODLUCK TECH SERVICE — SUPABASE POSTGRESQL DATABASE SCHEMA
-- =============================================================
-- Copy and run this script in your Supabase SQL Editor:
-- https://app.supabase.com/project/_/sql

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  condition TEXT NOT NULL DEFAULT 'UK Used',
  base_price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_status TEXT NOT NULL DEFAULT 'In Stock',
  description TEXT,
  warranty TEXT DEFAULT '6 Months Warranty',
  battery_health TEXT DEFAULT '90%+',
  sim_info TEXT DEFAULT 'Physical SIM + eSIM',
  is_featured INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. VARIATIONS TABLE
CREATE TABLE IF NOT EXISTS public.variations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  storage TEXT,
  ram TEXT,
  color TEXT,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_qty INT DEFAULT 5,
  sku TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCT IMAGES TABLE
CREATE TABLE IF NOT EXISTS public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  sort_order INT DEFAULT 0
);

-- 4. ACCESSORIES TABLE
CREATE TABLE IF NOT EXISTS public.accessories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  stock_qty INT DEFAULT 10,
  image_url TEXT,
  description TEXT,
  is_featured INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. PRODUCT ACCESSORIES LINK TABLE
CREATE TABLE IF NOT EXISTS public.product_accessories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  accessory_id BIGINT REFERENCES public.accessories(id) ON DELETE CASCADE
);

-- 6. BRANDS TABLE
CREATE TABLE IF NOT EXISTS public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  is_active INT DEFAULT 1
);

-- 7. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_method TEXT NOT NULL,
  state TEXT,
  city TEXT,
  address TEXT,
  notes TEXT,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  order_details JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. REPAIR REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.repair_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  email TEXT,
  location TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  storage TEXT,
  problem_type TEXT NOT NULL,
  problem_description TEXT,
  repair_preference TEXT DEFAULT 'Bring to store',
  preferred_date TEXT,
  diagnosis TEXT,
  estimated_cost NUMERIC(12, 2) DEFAULT 0.00,
  final_cost NUMERIC(12, 2) DEFAULT 0.00,
  internal_notes TEXT,
  images JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. SWAP / TRADE-IN REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.swap_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_code TEXT UNIQUE NOT NULL,
  request_type TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  location TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  storage TEXT NOT NULL,
  ram TEXT,
  color TEXT,
  battery_health TEXT,
  condition_notes TEXT,
  faults TEXT,
  asking_price NUMERIC(12, 2) DEFAULT 0.00,
  target_swap_phone TEXT,
  admin_offer NUMERIC(12, 2) DEFAULT 0.00,
  internal_notes TEXT,
  images JSONB,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  rating INT NOT NULL DEFAULT 5,
  comment TEXT NOT NULL,
  verified_purchase INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- =============================================================
-- SEED INITIAL DATA FOR NIGERIAN PHONE STORE INVENTORY
-- =============================================================

-- Default Store Settings
INSERT INTO public.settings (key, value) VALUES
  ('store_name', 'Goodluck Tech Service'),
  ('store_address', 'UPTH 18, Everyday Plaza, Choba, Port Harcourt, Rivers State'),
  ('whatsapp_number', '09012544042'),
  ('phone_number', '09012544042'),
  ('email', 'info@goodlucktech.ng')
ON CONFLICT (key) DO NOTHING;

-- Brands
INSERT INTO public.brands (name, logo_url) VALUES
  ('Apple', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg'),
  ('Samsung', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg'),
  ('Tecno', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Tecno_Mobile_logo.svg'),
  ('Infinix', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Infinix_logo.svg'),
  ('Google Pixel', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg')
ON CONFLICT (name) DO NOTHING;

-- Default Accessories
INSERT INTO public.accessories (title, category, price, stock_qty, image_url, description, is_featured) VALUES
  ('Apple 20W USB-C Fast Power Adapter', 'Chargers', 12500, 30, 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80', 'Original 20W fast charging plug for iPhones', 1),
  ('Apple AirPods Pro (2nd Gen)', 'Earbuds', 145000, 15, 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80', 'Active Noise Cancellation with MagSafe Charging Case', 1),
  ('Oraimo 10,000mAh Ultra Slim Power Bank', 'Power Banks', 18500, 25, 'https://images.unsplash.com/photo-1609592424074-1296c05b8ef2?w=600&auto=format&fit=crop&q=80', 'Dual USB fast output with LED battery indicator', 1),
  ('Samsung 25W Super Fast Wall Charger', 'Chargers', 11000, 20, 'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=600&auto=format&fit=crop&q=80', 'PPS super fast charger for Galaxy phones', 1),
  ('iPhone 15 Pro Max Clear MagSafe Case', 'Cases', 6500, 40, 'https://images.unsplash.com/photo-1541877944-ac82a091518a?w=600&auto=format&fit=crop&q=80', 'Anti-yellowing shockproof clear case with strong magnetic ring', 1),
  ('9D Curved Tempered Glass Screen Guard', 'Screen Protectors', 3500, 50, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80', 'Edge-to-edge explosion-proof glass protection', 1)
ON CONFLICT DO NOTHING;

-- Default Products
INSERT INTO public.products (id, title, brand, model, condition, base_price, stock_status, description, warranty, battery_health, sim_info, is_featured) VALUES
  (1, 'Apple iPhone 15 Pro Max', 'iPhone', 'iPhone 15 Pro Max', 'UK Used', 1150000.00, 'In Stock', 'Clean UK Used iPhone 15 Pro Max with Grade A Titanium finish. 100% factory unlocked, Face ID active, true tone display.', '6 Months Store Warranty', '94% Clean Original', 'Physical SIM + eSIM', 1),
  (2, 'Apple iPhone 14', 'iPhone', 'iPhone 14', 'UK Used', 580000.00, 'In Stock', 'Super clean UK Used iPhone 14 with Ceramic Shield glass. 100% factory unlocked, water resistance intact.', '6 Months Store Warranty', '91%', 'Physical SIM + eSIM', 1),
  (3, 'Apple iPhone 13', 'iPhone', 'iPhone 13', 'UK Used', 470000.00, 'In Stock', 'Pristine UK Used iPhone 13. Cinematic mode video recording, A15 Bionic chip.', '6 Months Store Warranty', '88%', 'Physical SIM + eSIM', 1),
  (4, 'Apple iPhone 12', 'iPhone', 'iPhone 12', 'UK Used', 360000.00, 'In Stock', 'Clean UK Used iPhone 12 with 5G connectivity and Super Retina OLED display.', '6 Months Store Warranty', '86%', 'Physical SIM + eSIM', 0),
  (5, 'Apple iPhone 11', 'iPhone', 'iPhone 11', 'UK Used', 265000.00, 'In Stock', 'Affordable clean UK Used iPhone 11. Dual 12MP ultra-wide camera.', '6 Months Store Warranty', '85%', 'Physical SIM + eSIM', 0),
  (6, 'Samsung Galaxy S24 Ultra 5G', 'Samsung', 'Galaxy S24 Ultra', 'Brand New', 1420000.00, 'In Stock', 'Brand New Sealed Samsung Galaxy S24 Ultra with Galaxy AI features and built-in S Pen.', '1 Year Samsung Warranty', '100% Brand New', 'Dual SIM', 1),
  (7, 'Tecno Camon 30 Pro 5G', 'Tecno', 'Camon 30 Pro', 'Brand New', 385000.00, 'In Stock', 'Brand New Sealed Tecno Camon 30 Pro 5G with 50MP Sony IMX890 Camera & 70W Ultra Fast Charge.', '13 Months Carlcare Warranty', '100% Brand New', 'Dual SIM', 1),
  (8, 'Infinix Note 40 Pro 4G', 'Infinix', 'Note 40 Pro', 'Brand New', 320000.00, 'In Stock', 'Brand New Sealed Infinix Note 40 Pro with 3D Curved AMOLED Display & 20W Wireless MagCharge.', '13 Months Carlcare Warranty', '100% Brand New', 'Dual SIM', 0),
  (9, 'Google Pixel 8 Pro', 'Google Pixel', 'Pixel 8 Pro', 'UK Used', 690000.00, 'In Stock', 'Mint condition UK Used Google Pixel 8 Pro with Tensor G3 chip and 50MP AI Triple Camera system.', '6 Months Store Warranty', '95%', 'Physical SIM + eSIM', 1)
ON CONFLICT (id) DO NOTHING;

-- Variations
INSERT INTO public.variations (product_id, storage, ram, color, price, stock_qty, sku) VALUES
  (1, '256GB', '8GB', 'Natural Titanium', 1150000.00, 3, 'IP15PM-256-NAT'),
  (1, '512GB', '8GB', 'Black Titanium', 1280000.00, 2, 'IP15PM-512-BLK'),
  (1, '1TB', '8GB', 'Blue Titanium', 1420000.00, 1, 'IP15PM-1TB-BLU'),
  (2, '128GB', '6GB', 'Midnight', 580000.00, 4, 'IP14-128-MID'),
  (2, '256GB', '6GB', 'Starlight', 640000.00, 3, 'IP14-256-STL'),
  (3, '128GB', '4GB', 'Pink', 470000.00, 5, 'IP13-128-PNK'),
  (3, '256GB', '4GB', 'Midnight', 525000.00, 3, 'IP13-256-MID'),
  (4, '64GB', '4GB', 'Black', 360000.00, 4, 'IP12-64-BLK'),
  (4, '128GB', '4GB', 'Blue', 410000.00, 3, 'IP12-128-BLU'),
  (5, '64GB', '4GB', 'Black', 265000.00, 6, 'IP11-64-BLK'),
  (5, '128GB', '4GB', 'White', 300000.00, 4, 'IP11-128-WHT'),
  (6, '256GB', '12GB', 'Titanium Black', 1420000.00, 2, 'S24U-256-BLK'),
  (6, '512GB', '12GB', 'Titanium Gray', 1580000.00, 2, 'S24U-512-GRY'),
  (7, '256GB', '12GB', 'Alps Snowy Silver', 385000.00, 5, 'TC30P-256-SLV'),
  (8, '256GB', '8GB', 'Vintage Green', 320000.00, 6, 'IN40P-256-GRN'),
  (9, '128GB', '12GB', 'Obsidian Black', 690000.00, 3, 'P8P-128-BLK')
ON CONFLICT DO NOTHING;

-- Product Images
INSERT INTO public.product_images (product_id, image_url, sort_order) VALUES
  (1, 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80', 0),
  (1, 'https://images.unsplash.com/photo-1695048133021-3995f7915c26?w=800&auto=format&fit=crop&q=80', 1),
  (2, 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&auto=format&fit=crop&q=80', 0),
  (3, 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&auto=format&fit=crop&q=80', 0),
  (4, 'https://images.unsplash.com/photo-1603891128711-11b4b0320d31?w=800&auto=format&fit=crop&q=80', 0),
  (5, 'https://images.unsplash.com/photo-1574944985070-8f30c4397e3c?w=800&auto=format&fit=crop&q=80', 0),
  (6, 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80', 0),
  (7, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80', 0),
  (8, 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80', 0),
  (9, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80', 0)
ON CONFLICT DO NOTHING;

-- Enable Public Access Row Level Security (RLS) Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accessories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repair_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swap_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public write access on products" ON public.products FOR ALL USING (true);

CREATE POLICY "Allow public read access on variations" ON public.variations FOR SELECT USING (true);
CREATE POLICY "Allow public write access on variations" ON public.variations FOR ALL USING (true);

CREATE POLICY "Allow public read access on product_images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Allow public write access on product_images" ON public.product_images FOR ALL USING (true);

CREATE POLICY "Allow public read access on accessories" ON public.accessories FOR SELECT USING (true);
CREATE POLICY "Allow public write access on accessories" ON public.accessories FOR ALL USING (true);

CREATE POLICY "Allow public read access on orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public write access on orders" ON public.orders FOR ALL USING (true);

CREATE POLICY "Allow public read access on repair_requests" ON public.repair_requests FOR SELECT USING (true);
CREATE POLICY "Allow public write access on repair_requests" ON public.repair_requests FOR ALL USING (true);

CREATE POLICY "Allow public read access on swap_requests" ON public.swap_requests FOR SELECT USING (true);
CREATE POLICY "Allow public write access on swap_requests" ON public.swap_requests FOR ALL USING (true);

CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public write access on settings" ON public.settings FOR ALL USING (true);
